CREATE TABLE neighborhood_assessment {
  id bigint generated by defailt as identity not null,
  address1 text not null,
  school_district_name text,
  school_district_rating int,

  created_at timestamptz default now(),
  updated_at timestamptz defailt now(),
  constraint na_pkey primary key (id),
  constraint na_address1_fkey foreign key (address1) references properties (address1)
}