-- ============================================
-- PROPERTY INSPECTION DATABASE SCHEMA
-- ============================================

-- Main inspections table
CREATE TABLE public.inspections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  address1 TEXT NOT NULL,
  inspection_date DATE NOT NULL,
  inspector_name TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT inspections_pkey PRIMARY KEY (id),
  CONSTRAINT inspections_address1_fkey FOREIGN KEY (address1) REFERENCES properties (address1)
);

-- ============================================
-- ENUM TYPES FOR INSPECTION FIELDS
-- ============================================

CREATE TYPE foundation_condition_enum AS ENUM (
  'excellent',
  'minor_cracks',
  'major_damage',
  'failing',
  'actively_crumbling'
);

CREATE TYPE plumbing_leak_severity_enum AS ENUM (
  'none',
  'minor',
  'major'
);

CREATE TYPE electrical_wiring_type_enum AS ENUM (
  'modern_copper',
  'aluminum',
  'knob_and_tube',
  'mixed',
  'unknown'
);

CREATE TYPE electrical_panel_type_enum AS ENUM (
  'standard',
  'federal_pacific',
  'zinsco',
  'other'
);

CREATE TYPE gfci_status_enum AS ENUM (
  'not_present',
  'present_nonfunctional',
  'functional'
);

CREATE TYPE flooring_condition_enum AS ENUM (
  'excellent',
  'good',
  'fair',
  'poor',
  'needs_replacement'
);

CREATE TYPE egress_window_status_enum AS ENUM (
  'compliant',
  'non_compliant_size',
  'non_compliant_operation',
  'not_present'
);

-- ============================================
-- STRUCTURAL & EXTERIOR INSPECTIONS
-- ============================================

-- Foundation, Structure & Roof
CREATE TABLE public.inspection_structural (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inspection_id BIGINT NOT NULL,

  -- Foundation & Structure
  foundation_condition foundation_condition_enum,
  walls_plumb_square BOOLEAN,
  no_previous_structural_repairs BOOLEAN,
  crawlspace_dry BOOLEAN,
  no_water_intrusion BOOLEAN,
  no_structural_wood_rot BOOLEAN,

  -- Roof
  roof_age_years INTEGER,
  roof_no_active_leaks BOOLEAN,
  roof_shingles_intact BOOLEAN,
  roof_no_sagging BOOLEAN,
  roof_flashing_intact BOOLEAN,
  roof_no_daylight_visible BOOLEAN,
  roof_no_water_stains BOOLEAN,
  roof_proper_ventilation BOOLEAN,
  chimney_sound BOOLEAN,
  gutters_attached BOOLEAN,
  gutters_clear BOOLEAN,
  downspouts_proper_drainage BOOLEAN,
  no_standing_water_ice_damage BOOLEAN,

  CONSTRAINT inspection_structural_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_structural_inspection_fkey FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE CASCADE
);

-- Exterior Walls, Siding, Windows & Doors
CREATE TABLE public.inspection_exterior (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inspection_id BIGINT NOT NULL,

  -- Exterior Walls & Siding
  siding_type TEXT,
  siding_no_damage BOOLEAN,
  siding_no_rot BOOLEAN,
  paint_good_condition BOOLEAN,
  caulking_intact BOOLEAN,
  masonry_joints_sound BOOLEAN,
  masonry_no_efflorescence BOOLEAN,
  masonry_watertight BOOLEAN,
  exterior_no_water_damage BOOLEAN,
  siding_sealed_weatherproofed BOOLEAN,
  exterior_no_pest_damage BOOLEAN,
  metal_no_rust BOOLEAN,

  -- Windows & Doors
  windows_no_broken_panes BOOLEAN,
  windows_proper_glazing BOOLEAN,
  window_frames_not_rotted BOOLEAN,
  windows_operate_smoothly BOOLEAN,
  window_locks_functional BOOLEAN,
  screens_present BOOLEAN,
  screens_good_repair BOOLEAN,
  exterior_doors_hang_properly BOOLEAN,
  exterior_doors_locks_functional BOOLEAN,
  door_frames_not_rotted BOOLEAN,
  weather_stripping_intact BOOLEAN,
  storm_doors_close_properly BOOLEAN,
  screen_doors_functional BOOLEAN,

  CONSTRAINT inspection_exterior_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_exterior_inspection_fkey FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE CASCADE
);

-- ============================================
-- GROUNDS & PARKING
-- ============================================

CREATE TABLE public.inspection_grounds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inspection_id BIGINT NOT NULL,

  -- Parking/Driveway
  parking_spaces_count INTEGER,
  parking_adequate BOOLEAN,
  paving_no_major_damage BOOLEAN,
  paved_no_potholes BOOLEAN,
  paving_cracks_sealed BOOLEAN,
  parking_properly_graded BOOLEAN,
  parking_line_markings_visible BOOLEAN,
  parking_curbs_intact BOOLEAN,
  parking_on_impervious_surface BOOLEAN,

  -- Walkways & Stairs
  walkways_no_trip_hazards BOOLEAN,
  sidewalks_good_repair BOOLEAN,
  walkways_no_wide_cracks BOOLEAN,
  walkways_proper_slope BOOLEAN,
  stairs_structurally_sound BOOLEAN,
  stairs_no_damage BOOLEAN,
  handrails_present_if_needed BOOLEAN,
  handrails_secure BOOLEAN,
  guardrails_present_if_needed BOOLEAN,
  porches_decks_sound BOOLEAN,
  deck_boards_secure BOOLEAN,
  porch_supports_not_rotted BOOLEAN,

  -- Landscaping & Drainage
  grass_maintained BOOLEAN,
  no_overgrown_vegetation BOOLEAN,
  trees_healthy BOOLEAN,
  tree_branches_clear_of_roof BOOLEAN,
  bushes_trimmed BOOLEAN,
  ground_slopes_away BOOLEAN,
  no_standing_water_foundation BOOLEAN,
  drainage_ditches_functional BOOLEAN,
  french_drains_functional BOOLEAN,
  surface_drains_clear BOOLEAN,
  no_dead_landscaping BOOLEAN,
  areas_needing_sod_mulch TEXT,
  property_free_of_debris BOOLEAN,

  -- Fencing & Security
  fences_sound BOOLEAN,
  gates_functional BOOLEAN,
  fence_posts_not_rotted BOOLEAN,
  entry_doors_secure_locks BOOLEAN,
  entry_doors_locked BOOLEAN,
  adequate_entry_lighting BOOLEAN,
  adequate_perimeter_lighting BOOLEAN,
  lighting_fixtures_operational BOOLEAN,
  motion_sensors_functional BOOLEAN,

  CONSTRAINT inspection_grounds_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_grounds_inspection_fkey FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE CASCADE
);

-- ============================================
-- BUILDING SYSTEMS
-- ============================================

-- HVAC System
CREATE TABLE public.inspection_hvac (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inspection_id BIGINT NOT NULL,

  hvac_system_type TEXT,
  hvac_system_age_years INTEGER,
  hvac_functioning BOOLEAN,
  hvac_maintenance_evidence BOOLEAN,
  hvac_last_service_date DATE,
  hvac_properly_vented BOOLEAN,
  hvac_no_rust_corrosion BOOLEAN,
  hvac_heat_exchanger_intact BOOLEAN,
  hvac_condensate_drain_clear BOOLEAN,
  hvac_ductwork_good_condition BOOLEAN,
  hvac_no_disconnected_ducts BOOLEAN,
  hvac_filters_clean BOOLEAN,
  hvac_thermostat_functional BOOLEAN,
  ac_condenser_operational BOOLEAN,
  ac_condenser_age_years INTEGER,
  co_detector_present BOOLEAN,

  CONSTRAINT inspection_hvac_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_hvac_inspection_fkey FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE CASCADE
);

-- Electrical System
CREATE TABLE public.inspection_electrical (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inspection_id BIGINT NOT NULL,

  electrical_service_amps INTEGER,
  electrical_wiring_type electrical_wiring_type_enum,
  electrical_panel_type electrical_panel_type_enum,
  electrical_service_adequate BOOLEAN,
  electrical_panel_accessible BOOLEAN,
  electrical_panel_labeled BOOLEAN,
  electrical_no_overheating BOOLEAN,
  electrical_no_double_taps BOOLEAN,
  electrical_no_rust BOOLEAN,
  electrical_proper_grounding BOOLEAN,
  electrical_no_amateur_wiring BOOLEAN,
  electrical_no_open_boxes BOOLEAN,
  electrical_meter_good_condition BOOLEAN,
  electrical_separate_meters BOOLEAN,

  CONSTRAINT inspection_electrical_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_electrical_inspection_fkey FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE CASCADE
);

-- Plumbing System
CREATE TABLE public.inspection_plumbing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inspection_id BIGINT NOT NULL,

  plumbing_main_line_type TEXT,
  plumbing_leak_severity plumbing_leak_severity_enum,
  plumbing_no_sewage_backup BOOLEAN,
  plumbing_no_polybutylene BOOLEAN,
  plumbing_no_galvanized_corrosion BOOLEAN,
  plumbing_no_sewer_replacement_needed BOOLEAN,
  plumbing_water_pressure_adequate BOOLEAN,
  plumbing_hot_water_available BOOLEAN,

  -- Water Heater
  water_heater_type TEXT,
  water_heater_age_years INTEGER,
  water_heater_properly_vented BOOLEAN,
  water_heater_tp_valve_present BOOLEAN,
  water_heater_tp_discharge_proper BOOLEAN,
  water_heater_no_rust BOOLEAN,
  water_heater_drain_pan_present BOOLEAN,

  -- Additional Plumbing
  water_shutoff_accessible BOOLEAN,
  water_meter_bonding_present BOOLEAN,
  sump_pump_functional BOOLEAN,
  sump_pump_check_valve BOOLEAN,
  plumbing_no_s_traps BOOLEAN,
  drains_flowing_properly BOOLEAN,

  CONSTRAINT inspection_plumbing_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_plumbing_inspection_fkey FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE CASCADE
);

-- ============================================
-- COMMON AREAS & SHARED SPACES
-- ============================================

CREATE TABLE public.inspection_common_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inspection_id BIGINT NOT NULL,

  -- Laundry Facilities
  has_shared_laundry BOOLEAN,
  laundry_clean_maintained BOOLEAN,
  laundry_adequate_ventilation BOOLEAN,
  laundry_dryer_vented_exterior BOOLEAN,
  laundry_gfci_outlets BOOLEAN,
  laundry_washers_working_count INTEGER,
  laundry_washers_broken_count INTEGER,
  laundry_dryers_working_count INTEGER,
  laundry_dryers_broken_count INTEGER,
  laundry_shutoffs_accessible BOOLEAN,
  laundry_no_water_damage BOOLEAN,
  laundry_floor_drain_present BOOLEAN,
  laundry_adequate_lighting BOOLEAN,
  laundry_trash_receptacle BOOLEAN,

  -- Hallways/Common Entries
  hallways_clean_unobstructed BOOLEAN,
  hallways_no_trip_hazards BOOLEAN,
  hallways_adequate_lighting BOOLEAN,
  hallways_lights_functional BOOLEAN,
  hallways_walls_floors_good BOOLEAN,
  hallways_handrails_secure BOOLEAN,
  hallways_exit_signs_lit BOOLEAN,

  -- Storage Areas
  storage_areas_secure BOOLEAN,
  storage_areas_dry BOOLEAN,
  storage_no_water_damage BOOLEAN,
  storage_adequate_lighting BOOLEAN,
  storage_no_hazardous_materials BOOLEAN,
  storage_no_excessive_clutter BOOLEAN,

  -- Mailboxes
  mailboxes_present_each_unit BOOLEAN,
  mailboxes_properly_labeled BOOLEAN,
  mailboxes_locks_functional BOOLEAN,
  mailboxes_usps_approved BOOLEAN,

  CONSTRAINT inspection_common_areas_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_common_areas_inspection_fkey FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE CASCADE
);

-- ============================================
-- SAFETY & COMPLIANCE
-- ============================================

CREATE TABLE public.inspection_safety (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inspection_id BIGINT NOT NULL,

  -- Fire Safety
  fire_smoke_detectors_common BOOLEAN,
  fire_extinguishers_present BOOLEAN,
  fire_extinguishers_inspected BOOLEAN,
  fire_exits_marked BOOLEAN,
  fire_exits_unobstructed BOOLEAN,
  fire_vehicle_access_clear BOOLEAN,
  fire_lanes_marked BOOLEAN,
  fire_garage_separation_proper BOOLEAN,

  -- General Property
  property_no_rubbish BOOLEAN,
  property_trash_containers_serviceable BOOLEAN,
  property_trash_containers_located BOOLEAN,
  property_trash_pickup_regular BOOLEAN,
  property_clean_sanitary BOOLEAN,
  property_numbers_visible BOOLEAN,
  property_no_rodents BOOLEAN,
  property_no_insects BOOLEAN,
  property_no_inoperative_vehicles BOOLEAN,
  property_all_vehicles_licensed BOOLEAN,
  property_no_prohibited_parking BOOLEAN,
  property_pools_maintained BOOLEAN,
  property_pool_fenced BOOLEAN,

  CONSTRAINT inspection_safety_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_safety_inspection_fkey FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE CASCADE
);

-- ============================================
-- ACCESSORY STRUCTURES
-- ============================================

CREATE TABLE public.inspection_accessory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inspection_id BIGINT NOT NULL,

  -- Garage/Shed
  garage_shed_structurally_sound BOOLEAN,
  garage_shed_no_deterioration BOOLEAN,
  garage_shed_roof_weathertight BOOLEAN,
  garage_shed_doors_functional BOOLEAN,
  garage_shed_hardware_functional BOOLEAN,
  garage_shed_windows_intact BOOLEAN,
  garage_shed_siding_acceptable BOOLEAN,
  garage_shed_electrical_safe BOOLEAN,
  garage_shed_no_fire_hazards BOOLEAN,
  garage_shed_flammables_stored_properly BOOLEAN,
  garage_shed_not_filled_rubbish BOOLEAN,
  garage_shed_no_garbage BOOLEAN,

  CONSTRAINT inspection_accessory_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_accessory_inspection_fkey FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE CASCADE
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX idx_inspection_structural_inspection_id ON inspection_structural(inspection_id);
CREATE INDEX idx_inspection_exterior_inspection_id ON inspection_exterior(inspection_id);
CREATE INDEX idx_inspection_grounds_inspection_id ON inspection_grounds(inspection_id);
CREATE INDEX idx_inspection_hvac_inspection_id ON inspection_hvac(inspection_id);
CREATE INDEX idx_inspection_electrical_inspection_id ON inspection_electrical(inspection_id);
CREATE INDEX idx_inspection_plumbing_inspection_id ON inspection_plumbing(inspection_id);
CREATE INDEX idx_inspection_common_areas_inspection_id ON inspection_common_areas(inspection_id);
CREATE INDEX idx_inspection_safety_inspection_id ON inspection_safety(inspection_id);
CREATE INDEX idx_inspection_accessory_inspection_id ON inspection_accessory(inspection_id);
CREATE INDEX idx_inspections_address1 ON inspections(address1);
CREATE INDEX idx_inspections_inspection_date ON inspections(inspection_date);


-- ============================================
-- UNIT-LEVEL INSPECTION DATABASE SCHEMA
-- ============================================

-- Main unit inspections table
CREATE TABLE public.unit_inspections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  address1 TEXT NOT NULL,
  unit_identifier TEXT NOT NULL,
  inspection_date DATE NOT NULL,
  inspector_name TEXT,
  notes TEXT,
  property_inspection_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  CONSTRAINT unit_inspections_pkey PRIMARY KEY (id),
  CONSTRAINT unit_inspections_rent_estimates_fkey FOREIGN KEY (address1, unit_identifier) REFERENCES rent_estimates (address1, unit_identifier),
  CONSTRAINT unit_inspections_property_inspection_fkey FOREIGN KEY (property_inspection_id) REFERENCES inspections (id)
);

-- ============================================
-- ENTRY & LIVING SPACES
-- ============================================

CREATE TABLE public.unit_inspection_entry_living (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unit_inspection_id BIGINT NOT NULL,

  -- Floors
  floors_no_active_water_damage BOOLEAN,
  flooring_type TEXT,
  flooring_condition flooring_condition_enum,
  flooring_safe_intact BOOLEAN,
  floors_no_soft_spots BOOLEAN,
  floors_no_squeaking BOOLEAN,

  -- Walls
  walls_no_major_damage BOOLEAN,
  walls_no_major_cracks BOOLEAN,
  walls_plaster_not_crumbling BOOLEAN,
  walls_paint_acceptable BOOLEAN,
  walls_no_peeling_paint BOOLEAN,
  walls_drywall_attached BOOLEAN,
  walls_no_moisture_damage BOOLEAN,
  walls_no_previous_water_damage BOOLEAN,

  -- Ceilings
  ceilings_no_active_leaks BOOLEAN,
  ceilings_no_major_cracks BOOLEAN,
  ceilings_no_sagging BOOLEAN,
  ceilings_no_water_stains BOOLEAN,
  ceilings_no_loose_material BOOLEAN,
  ceiling_fixtures_secure BOOLEAN,

  -- Windows
  windows_all_open_close BOOLEAN,
  windows_no_broken_glass BOOLEAN,
  window_frames_good_condition BOOLEAN,
  window_sills_not_rotted BOOLEAN,
  window_locks_functional BOOLEAN,
  windows_low_have_locks BOOLEAN,
  windows_stay_open BOOLEAN,
  window_screens_present BOOLEAN,
  window_screens_good_repair BOOLEAN,
  windows_no_condensation BOOLEAN,
  windows_proper_glazing BOOLEAN,

  -- Doors & Hardware
  interior_doors_hang_properly BOOLEAN,
  doors_open_close_smoothly BOOLEAN,
  door_hardware_functional BOOLEAN,
  door_locks_work BOOLEAN,
  closet_doors_functional BOOLEAN,
  doors_no_sticking BOOLEAN,
  door_frames_no_damage BOOLEAN,
  strike_plates_installed BOOLEAN,
  doorstops_present BOOLEAN,

  CONSTRAINT unit_inspection_entry_living_pkey PRIMARY KEY (id),
  CONSTRAINT unit_inspection_entry_living_unit_fkey FOREIGN KEY (unit_inspection_id) REFERENCES unit_inspections (id) ON DELETE CASCADE
);

-- ============================================
-- KITCHEN
-- ============================================

CREATE TABLE public.unit_inspection_kitchen (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unit_inspection_id BIGINT NOT NULL,

  -- Kitchen Condition
  kitchen_adequate_size BOOLEAN,
  kitchen_adequate_light BOOLEAN,
  kitchen_proper_ventilation BOOLEAN,
  cabinets_secure_functional BOOLEAN,
  cabinet_doors_open_smoothly BOOLEAN,
  cabinet_boxes_not_damaged BOOLEAN,
  cabinet_hardware_functional BOOLEAN,
  countertops_good_condition BOOLEAN,
  countertops_no_major_damage BOOLEAN,
  backsplash_present_intact BOOLEAN,

  -- Kitchen Sink & Plumbing
  sink_good_condition BOOLEAN,
  sink_faucet_operational BOOLEAN,
  sink_hot_cold_working BOOLEAN,
  sink_no_leaks BOOLEAN,
  sink_drain_flows BOOLEAN,
  sink_p_trap_present BOOLEAN,
  sink_shutoff_valves_present BOOLEAN,
  garbage_disposal_works BOOLEAN,
  garbage_disposal_not_leaking BOOLEAN,
  dishwasher_drain_proper BOOLEAN,

  -- Kitchen Electrical
  kitchen_gfci_status gfci_status_enum,
  kitchen_sufficient_outlets BOOLEAN,
  kitchen_all_outlets_functional BOOLEAN,
  kitchen_no_overloaded_circuits BOOLEAN,
  kitchen_light_fixtures_operational BOOLEAN,

  -- Refrigerator
  fridge_present BOOLEAN,
  fridge_powers_on BOOLEAN,
  fridge_cools_properly BOOLEAN,
  fridge_freezer_works BOOLEAN,
  fridge_door_seals_intact BOOLEAN,
  fridge_no_frost_buildup BOOLEAN,
  fridge_interior_clean BOOLEAN,
  fridge_shelves_present BOOLEAN,
  fridge_light_works BOOLEAN,
  fridge_no_unusual_noises BOOLEAN,
  fridge_ice_maker_functional BOOLEAN,
  fridge_water_dispenser_functional BOOLEAN,

  -- Stove/Oven/Range
  stove_present BOOLEAN,
  stove_type TEXT,
  stove_all_burners_work BOOLEAN,
  stove_grates_present BOOLEAN,
  stove_drip_pans_present BOOLEAN,
  oven_heats_properly BOOLEAN,
  oven_door_operates_smoothly BOOLEAN,
  oven_door_seal_intact BOOLEAN,
  oven_broiler_functional BOOLEAN,
  oven_light_works BOOLEAN,
  oven_timer_functional BOOLEAN,
  stove_control_knobs_functional BOOLEAN,
  oven_self_cleaning_works BOOLEAN,
  stove_no_gas_smell BOOLEAN,
  stove_anti_tip_installed BOOLEAN,

  -- Dishwasher
  dishwasher_present BOOLEAN,
  dishwasher_runs_cycle BOOLEAN,
  dishwasher_fills_properly BOOLEAN,
  dishwasher_drains_completely BOOLEAN,
  dishwasher_no_leaks BOOLEAN,
  dishwasher_racks_slide BOOLEAN,
  dishwasher_racks_intact BOOLEAN,
  dishwasher_spray_arms_spin BOOLEAN,
  dishwasher_detergent_dispenser_works BOOLEAN,
  dishwasher_door_latch_functional BOOLEAN,
  dishwasher_no_unusual_noises BOOLEAN,
  dishwasher_heats_water BOOLEAN,

  -- Microwave
  microwave_present BOOLEAN,
  microwave_powers_on BOOLEAN,
  microwave_heats_properly BOOLEAN,
  microwave_turntable_rotates BOOLEAN,
  microwave_door_closes BOOLEAN,
  microwave_light_works BOOLEAN,
  microwave_vent_fan_works BOOLEAN,
  microwave_controls_functional BOOLEAN,
  microwave_no_sparking BOOLEAN,

  CONSTRAINT unit_inspection_kitchen_pkey PRIMARY KEY (id),
  CONSTRAINT unit_inspection_kitchen_unit_fkey FOREIGN KEY (unit_inspection_id) REFERENCES unit_inspections (id) ON DELETE CASCADE
);

-- ============================================
-- BATHROOMS (Multiple per unit)
-- ============================================

CREATE TABLE public.unit_inspection_bathrooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unit_inspection_id BIGINT NOT NULL,
  bathroom_number INTEGER NOT NULL,

  -- Toilet
  toilet_no_severe_issues BOOLEAN,
  toilet_flushes_properly BOOLEAN,
  toilet_tank_fills_properly BOOLEAN,
  toilet_no_running_water BOOLEAN,
  toilet_no_leak_at_base BOOLEAN,
  toilet_no_leak_at_tank BOOLEAN,
  toilet_seat_present BOOLEAN,
  toilet_bowl_not_cracked BOOLEAN,
  toilet_handle_functional BOOLEAN,
  toilet_no_wobbling BOOLEAN,

  -- Sink/Vanity
  bathroom_sink_not_cracked BOOLEAN,
  bathroom_faucet_operational BOOLEAN,
  bathroom_sink_hot_cold_working BOOLEAN,
  bathroom_sink_pressure_adequate BOOLEAN,
  bathroom_sink_drain_flows BOOLEAN,
  bathroom_sink_stopper_works BOOLEAN,
  bathroom_sink_no_leaks BOOLEAN,
  bathroom_sink_p_trap_present BOOLEAN,
  bathroom_sink_shutoffs_present BOOLEAN,
  bathroom_vanity_secure BOOLEAN,
  bathroom_cabinet_doors_functional BOOLEAN,
  bathroom_cabinet_no_water_damage BOOLEAN,

  -- Tub/Shower
  tub_shower_not_cracked BOOLEAN,
  tub_shower_no_chips BOOLEAN,
  tub_shower_faucet_operational BOOLEAN,
  tub_shower_hot_cold_working BOOLEAN,
  tub_shower_pressure_adequate BOOLEAN,
  showerhead_functional BOOLEAN,
  tub_shower_drain_flows BOOLEAN,
  tub_shower_no_standing_water BOOLEAN,
  tub_shower_caulking_intact BOOLEAN,
  tub_shower_grout_good_condition BOOLEAN,
  tub_shower_tile_secure BOOLEAN,
  tub_shower_no_ceiling_damage_below BOOLEAN,
  shower_door_curtain_secure BOOLEAN,
  tub_spout_secure BOOLEAN,
  tub_diverter_works BOOLEAN,
  tub_access_panel_present BOOLEAN,

  -- Walls/Floor
  bathroom_floor_no_water_damage BOOLEAN,
  bathroom_floor_good_condition BOOLEAN,
  bathroom_floor_no_soft_spots BOOLEAN,
  bathroom_floor_tile_secure BOOLEAN,
  bathroom_walls_good_condition BOOLEAN,
  bathroom_walls_no_peeling BOOLEAN,
  bathroom_walls_water_resistant BOOLEAN,
  bathroom_ceiling_good_condition BOOLEAN,
  bathroom_ceiling_no_moisture_damage BOOLEAN,

  -- Electrical & Ventilation
  bathroom_gfci_status gfci_status_enum,
  bathroom_light_operational BOOLEAN,
  bathroom_vanity_light_functional BOOLEAN,
  bathroom_exhaust_fan_present BOOLEAN,
  bathroom_fan_vents_exterior BOOLEAN,
  bathroom_adequate_ventilation BOOLEAN,

  -- General
  bathroom_mirror_present BOOLEAN,
  bathroom_towel_bars_secure BOOLEAN,
  bathroom_medicine_cabinet_functional BOOLEAN,
  bathroom_adequate_storage BOOLEAN,

  CONSTRAINT unit_inspection_bathrooms_pkey PRIMARY KEY (id),
  CONSTRAINT unit_inspection_bathrooms_unit_fkey FOREIGN KEY (unit_inspection_id) REFERENCES unit_inspections (id) ON DELETE CASCADE
);

-- ============================================
-- BEDROOMS (Multiple per unit)
-- ============================================

CREATE TABLE public.unit_inspection_bedrooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unit_inspection_id BIGINT NOT NULL,
  bedroom_number INTEGER NOT NULL,

  -- Size & Configuration
  bedroom_adequate_size BOOLEAN,
  bedroom_private_room BOOLEAN,
  bedroom_separate_from_access BOOLEAN,
  bedroom_door_closes_locks BOOLEAN,
  bedroom_window_adequate_light BOOLEAN,

  -- Egress Window
  egress_window_status egress_window_status_enum,

  -- Closet
  closet_present BOOLEAN,
  closet_adequate_size BOOLEAN,
  closet_door_functional BOOLEAN,
  closet_rod_shelving_present BOOLEAN,
  closet_light_fixture BOOLEAN,

  -- Electrical
  bedroom_outlets_adequate BOOLEAN,
  bedroom_outlets_functional BOOLEAN,
  bedroom_light_operational BOOLEAN,
  bedroom_ceiling_fan_works BOOLEAN,

  -- Safety
  bedroom_smoke_detector_installed BOOLEAN,
  bedroom_smoke_detector_functional BOOLEAN,
  bedroom_co_detector_present BOOLEAN,
  bedroom_adequate_lighting BOOLEAN,

  CONSTRAINT unit_inspection_bedrooms_pkey PRIMARY KEY (id),
  CONSTRAINT unit_inspection_bedrooms_unit_fkey FOREIGN KEY (unit_inspection_id) REFERENCES unit_inspections (id) ON DELETE CASCADE
);

-- ============================================
-- UNIT SYSTEMS
-- ============================================

CREATE TABLE public.unit_inspection_systems (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unit_inspection_id BIGINT NOT NULL,

  -- Heating
  heat_source TEXT,
  heating_radiators_functional BOOLEAN,
  heating_vents_present BOOLEAN,
  heating_adequate BOOLEAN,
  heating_thermostat_functional BOOLEAN,
  heating_thermostat_accessible BOOLEAN,
  heating_sources_not_blocked BOOLEAN,

  -- Cooling
  cooling_ac_type TEXT,
  cooling_central_functional BOOLEAN,
  cooling_window_units_functional BOOLEAN,
  cooling_adequate BOOLEAN,

  -- Electrical Panel/Service
  electrical_panel_accessible BOOLEAN,
  electrical_breakers_labeled BOOLEAN,
  electrical_subpanel_good_condition BOOLEAN,
  electrical_no_double_taps BOOLEAN,
  electrical_proper_capacity BOOLEAN,

  -- General Electrical
  electrical_all_outlets_functional BOOLEAN,
  electrical_grounded_outlets BOOLEAN,
  electrical_no_loose_outlets BOOLEAN,
  electrical_cover_plates_present BOOLEAN,
  electrical_switches_functional BOOLEAN,
  electrical_fixtures_operational BOOLEAN,
  electrical_no_exposed_wiring BOOLEAN,
  electrical_no_amateur_work BOOLEAN,
  electrical_sufficient_outlets BOOLEAN,

  -- Plumbing
  plumbing_hot_water_all_fixtures BOOLEAN,
  plumbing_pressure_adequate BOOLEAN,
  plumbing_all_faucets_functional BOOLEAN,
  plumbing_no_visible_leaks BOOLEAN,
  plumbing_all_drains_flow BOOLEAN,
  plumbing_no_sewer_gas BOOLEAN,
  plumbing_no_past_water_damage BOOLEAN,
  plumbing_shutoff_accessible BOOLEAN,

  CONSTRAINT unit_inspection_systems_pkey PRIMARY KEY (id),
  CONSTRAINT unit_inspection_systems_unit_fkey FOREIGN KEY (unit_inspection_id) REFERENCES unit_inspections (id) ON DELETE CASCADE
);

-- ============================================
-- UNIT-SPECIFIC APPLIANCES
-- ============================================

CREATE TABLE public.unit_inspection_appliances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unit_inspection_id BIGINT NOT NULL,

  -- Washer
  washer_present BOOLEAN,
  washer_hookups_only BOOLEAN,
  washer_fills_properly BOOLEAN,
  washer_agitates_spins BOOLEAN,
  washer_drains_completely BOOLEAN,
  washer_no_leaks BOOLEAN,
  washer_all_cycles_functional BOOLEAN,
  washer_door_lid_operates BOOLEAN,
  washer_no_unusual_noises BOOLEAN,
  washer_properly_vented BOOLEAN,

  -- Dryer
  dryer_present BOOLEAN,
  dryer_hookups_only BOOLEAN,
  dryer_type TEXT,
  dryer_heats_properly BOOLEAN,
  dryer_drum_rotates BOOLEAN,
  dryer_all_cycles_functional BOOLEAN,
  dryer_door_closes BOOLEAN,
  dryer_lint_trap_present BOOLEAN,
  dryer_vented_to_exterior BOOLEAN,
  dryer_vent_not_crushed BOOLEAN,
  dryer_no_lint_buildup BOOLEAN,
  dryer_no_gas_smell BOOLEAN,

  CONSTRAINT unit_inspection_appliances_pkey PRIMARY KEY (id),
  CONSTRAINT unit_inspection_appliances_unit_fkey FOREIGN KEY (unit_inspection_id) REFERENCES unit_inspections (id) ON DELETE CASCADE
);

-- ============================================
-- SAFETY & CODE COMPLIANCE
-- ============================================

CREATE TABLE public.unit_inspection_safety (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unit_inspection_id BIGINT NOT NULL,

  -- Life Safety
  safety_smoke_detector_each_bedroom BOOLEAN,
  safety_smoke_detector_outside_sleeping BOOLEAN,
  safety_smoke_detector_each_level BOOLEAN,
  safety_all_smoke_detectors_functional BOOLEAN,
  safety_co_detector_present BOOLEAN,
  safety_co_detector_functional BOOLEAN,
  safety_proper_egress_all_rooms BOOLEAN,
  safety_exit_path_clear BOOLEAN,
  safety_secondary_egress_bedrooms BOOLEAN,

  -- General Unit Condition
  unit_clean_sanitary BOOLEAN,
  unit_no_pest_infestation BOOLEAN,
  unit_no_rodent_evidence BOOLEAN,
  unit_no_bed_bugs BOOLEAN,
  unit_no_water_damage BOOLEAN,
  unit_no_mold_visible BOOLEAN,
  unit_no_musty_odors BOOLEAN,
  unit_adequate_ventilation BOOLEAN,
  unit_all_surfaces_safe BOOLEAN,
  unit_no_tripping_hazards BOOLEAN,
  unit_interior_stairs_handrails BOOLEAN,
  unit_handrails_secure BOOLEAN,

  CONSTRAINT unit_inspection_safety_pkey PRIMARY KEY (id),
  CONSTRAINT unit_inspection_safety_unit_fkey FOREIGN KEY (unit_inspection_id) REFERENCES unit_inspections (id) ON DELETE CASCADE
);

-- ============================================
-- STORAGE & OTHER FEATURES
-- ============================================

CREATE TABLE public.unit_inspection_storage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unit_inspection_id BIGINT NOT NULL,

  -- Storage
  storage_adequate_closet_space BOOLEAN,
  storage_hall_closet_present BOOLEAN,
  storage_linen_storage_available BOOLEAN,
  storage_additional_space TEXT,
  storage_areas_dry BOOLEAN,
  storage_accessible BOOLEAN,

  -- Other Features
  patio_balcony_access BOOLEAN,
  patio_balcony_safe BOOLEAN,
  patio_balcony_railings_secure BOOLEAN,
  outdoor_outlet_functional BOOLEAN,

  CONSTRAINT unit_inspection_storage_pkey PRIMARY KEY (id),
  CONSTRAINT unit_inspection_storage_unit_fkey FOREIGN KEY (unit_inspection_id) REFERENCES unit_inspections (id) ON DELETE CASCADE
);

-- ============================================
-- INDEXES FOR UNIT INSPECTIONS
-- ============================================

CREATE INDEX idx_unit_inspections_address1_unit ON unit_inspections(address1, unit_identifier);
CREATE INDEX idx_unit_inspections_property_inspection_id ON unit_inspections(property_inspection_id);
CREATE INDEX idx_unit_inspections_inspection_date ON unit_inspections(inspection_date);
CREATE INDEX idx_unit_inspection_entry_living_unit_id ON unit_inspection_entry_living(unit_inspection_id);
CREATE INDEX idx_unit_inspection_kitchen_unit_id ON unit_inspection_kitchen(unit_inspection_id);
CREATE INDEX idx_unit_inspection_bathrooms_unit_id ON unit_inspection_bathrooms(unit_inspection_id);
CREATE INDEX idx_unit_inspection_bedrooms_unit_id ON unit_inspection_bedrooms(unit_inspection_id);
CREATE INDEX idx_unit_inspection_systems_unit_id ON unit_inspection_systems(unit_inspection_id);
CREATE INDEX idx_unit_inspection_appliances_unit_id ON unit_inspection_appliances(unit_inspection_id);
CREATE INDEX idx_unit_inspection_safety_unit_id ON unit_inspection_safety(unit_inspection_id);
CREATE INDEX idx_unit_inspection_storage_unit_id ON unit_inspection_storage(unit_inspection_id);
